language: java

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "burst-apps-team"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=burst-apps-team -Dsonar.projectKey=burst-apps-team_burstcoin -Dsonar.login=$SONAR_KEY -Dsonar.verbose=true

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false
