DROP INDEX IF EXISTS transaction_recipient_id_amount_height_idx;
DROP INDEX IF EXISTS transaction_recipient_id_sender_id_idx;
DROP INDEX IF EXISTS tx_sender_type;
DROP INDEX IF EXISTS tx_block_id_index;
DROP INDEX IF EXISTS block_generator_id_idx;
DROP INDEX IF EXISTS subscription_time_next_index;
DROP INDEX IF EXISTS subscription_latest_index;
DROP INDEX IF EXISTS subscription_id_latest_idx;
DROP INDEX IF EXISTS account_asset_quantity_idx;
DROP INDEX IF EXISTS account_asset_assetid_latest_idx;
DROP INDEX IF EXISTS at_latest_idx;
CREATE INDEX IF NOT EXISTS reward_recip_assign_acc_latest_height_idx ON reward_recip_assign (account_id, latest, height);
CREATE INDEX IF NOT EXISTS at_id_latest_idx ON at (id, latest);
CREATE INDEX IF NOT EXISTS account_balance_latest_balance_idx ON account_balance (latest, balance);
CREATE INDEX IF NOT EXISTS account_asset_asset_latest_quantity_account_idx  ON account_asset (asset_id, latest, quantity DESC, account_id ASC);
CREATE INDEX IF NOT EXISTS tx_refhash_type_subtype_height_idx ON transaction (referenced_transaction_fullhash, type, subtype, height);
CREATE INDEX IF NOT EXISTS tx_height_id_idx ON transaction (height, id);
CREATE INDEX IF NOT EXISTS tx_sender_type_subtype_height_idx ON transaction (sender_id, type, subtype, height);
CREATE INDEX IF NOT EXISTS subscription_latest_next_id_idx ON subscription (latest, time_next, id);