version: 1
update_configs:
  - package_manager: "java:gradle"
    directory: "/"
    update_schedule: "weekly"
    target_branch: "develop"
    ignored_updates:
      - match:
          dependency_name: "org.flywaydb:flyway-core"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
